# Generated by Django 2.0.4 on 2018-05-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_token', models.CharField(max_length=20, verbose_name='Price per token')),
                ('n_tokens', models.CharField(max_length=20, verbose_name='Tokens')),
                ('fees', models.CharField(max_length=20, verbose_name='fees')),
                ('date', models.DateTimeField(verbose_name='Transaction Date')),
                ('exchange_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_exchange_coin', to='exchanges.ExchangeCoin')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=20, verbose_name='Transaction type')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_transaction_method', to='transactions.TransactionMethod'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_price', to='people.UserProfile'),
        ),
    ]
