# Generated by Django 2.0.4 on 2018-05-04 16:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_invested', models.FloatField(verbose_name='Value Insvested')),
                ('fee', models.PositiveSmallIntegerField(default=0, verbose_name='Fee')),
                ('contract_duration', models.CharField(choices=[('6_MONTH', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEAR', '2 Years')], default='1_YEAR', max_length=100, verbose_name='Contract Duration')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('value_current', models.FloatField(verbose_name='Current Value')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('MN', 'Manager'), ('FU', 'User of the Fung')], default='FU', max_length=100, unique=True, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.UserProfile'),
        ),
    ]
