# Generated by Django 2.0.4 on 2018-05-30 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_invested', models.FloatField(verbose_name='Value Insvested')),
                ('fee', models.PositiveSmallIntegerField(default=0, verbose_name='Fee')),
                ('contract_duration', models.CharField(choices=[('6_MONTH', '6 Months'), ('1_YEAR', '1 Year'), ('2_YEAR', '2 Years'), ('UNLIMITED', 'Unlimited')], default='1_YEAR', max_length=100, verbose_name='Contract Duration')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Start Date')),
                ('value_current', models.FloatField(verbose_name='Current Value')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
