# Generated by Django 2.0.4 on 2018-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Exchange Name')),
                ('url', models.CharField(max_length=100, unique=True, verbose_name='Exchange URL')),
                ('api', models.CharField(max_length=100, unique=True, verbose_name='Exchange Api')),
                ('coin_change', models.ManyToManyField(to='coins.CoinChange')),
            ],
        ),
    ]
