# Generated by Django 2.0.4 on 2018-05-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Coin name')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Coin key')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
        migrations.CreateModel(
            name='CoinChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinchange_coin', to='coins.Coin')),
                ('coin_to_change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinchange_coin_to_change', to='coins.Coin')),
            ],
        ),
    ]
